version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: social_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_admin -d social"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    command: -path=/migrations -database ${DATABASE_URL} up
    volumes:
      - ../migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  social-app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      HTTP_ADDR: ":8080"
    depends_on:
      - postgres
      - migrate
    env_file:
      - ../.env
    ports:
      - "${APP_PORT}:8080"

volumes:
  postgres_data: